version: "3"
services:
  flask-app:
    container_name: flask-app
    build:
      context: .
    command: python wsgi.py
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app