version: "3"
services:
  flask-app:
    container_name: flask-app
    build:
      context: .
    command: python wsgi.py
    environment:
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - my_network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge